
DROP TABLE IF EXISTS Conversion_Factor;
create table Conversion_Factor(ID integer generated by default as identity, countryCode VARCHAR(2) not null, countryfactor  DOUBLE not null, primary key (ID));
INSERT INTO Conversion_Factor(countryCode,countryfactor) VALUES ('US','75.0');
INSERT INTO Conversion_Factor(countryCode,countryfactor) VALUES ('BT','100.0');
INSERT INTO Conversion_Factor(countryCode,countryfactor) VALUES ('AU','51');
commit;